### PR TITLE
resolved

### PR DESCRIPTION
**Pull request by Kalimbak**
What does this PR do?
Creates or updates the user's profile

Description of Task to be completed?
As operator or driver, I want to be able to update information on my profile, so that others could see updated information about me.
Appropriate error messages are displayed on unsuccessful attempts

How should this be manually tested?
git pull this branch
run npm install
check env.example file and add JWT_SECRET and JWT_EXPIRES_IN to your .env file
Do migrations with npm run migrate
run npx sequelize-cli db:seed:all to create pre-configured credentials for seeders
run npm run dev
Test these routes
POST /api/v1/users/:id/update/ in POSTMAN or any other platform for using API

### CODE REVIEW

**Review by kwizeradev — APPROVED** [review]

**Review by Anguandia — COMMENTED** [review]
Hello @Kalimbak, good work and apologies for the delay. Please note that image upload failed, I used my personal cloudinary config details. Also note the following: 
- Auth should be more of a middleware, not controller. All user-related controller functions are in the User controller
- Harmonize input name casing eg firstName in registration vs firstname in profile. 
- Profile has mixed casing, eg lastname (lower) profilePic (camel)
- Rebase this PR and solicit one more review
- Gender is a hazy line in today's world and shouln't be mandatory in completing or updating one's profile
- Sync with the current owner of the corresponding task in the front end for any further change requests
- Solicit one more peer review

**Comment by Anguandia** [comment]
@aimelive , we need your review here

**Review by aimelive — APPROVED** [review]
Review added!

**Review by furebo — CHANGES_REQUESTED** [review]
Hi, Please rebase the develop and resolve the conflicts

**Review by furebo — CHANGES_REQUESTED** [review]
Hi, Please rebase the develop and resolve the conflicts

**Review by furebo — APPROVED** [review]

**Pull request merged**
