### PR TITLE
set permissions on a role [New branch]

### PR DESCRIPTION
**Pull request by UmuhireJessie**
### What does this PR do?
- CRUD operation on role, permissions
- Assign permissions to a role
- Assign a user a particular role in the Database
### Description of Task to be completed?
- Documenting API
- Testing API
### How should this be manually tested?
- After cloning the repo run `npm i` to install all packages
- For Windows users refer an extra step for installing [`redis`](https://www.youtube.com/watch?v=188Fy-oCw4w&ab_channel=ProgrammingKnowledge2)
- use postman to test different endpoints present in [`index.js`](https://github.com/atlp-rwanda/Dominators-Phantom-BE/blob/develop/src/routes/index.js)
- Run `npm run migrate` to migrate all models in the local database
- Run `npm run seed` to populate the tables with seeders' values
- Run `npm run dev` to start the server manually
- use `http://localhost:3000/api/v1/login` to log in by using admin credentials present in the seeder of the user table. (Change the port **3000** to adhere to your chosen port)
- After login and adding Authorisation in headers, insert the URL with the port and the method e.g., `http://localhost:3000/api/v1/permissions` and `GET`
- The response will be seen containing a list of permissions in the database. For example:
  ``` 
  {
    "Message": "success",
    "code": 200,
    "record": {
        "allPermissions": [
            {
                "permission_id": "0438c355-232e-440b-9ff2-8145c1df9ec1",
                "name": "add role",
                "description": "adding a new role previledge",
                "createdAt": "2022-06-24T12:47:10.731Z",
                "updatedAt": "2022-06-24T12:47:10.731Z"
            }
         ]
      "count": 1
       }
   }  

- If now the logged-in admin creates a new role and assigns the role to a user, the user by default has no permission.
The response will change to a 403 Forbidden
```
{
    "Message": "fail",
    "code": 403,
    "record": {
        "message": "You do not have this permission!"
    }
}
```

### Any background context you want to provide?
Use of permissions that are in the database while checking if a logged-in user is permitted to do an operation. Permissions used are in an object for now.
### What are the relevant pivotal tracker stories?

### Screenshots (if appropriate)

### Questions:

### CODE REVIEW

**Review by aimelive — APPROVED** [review]

**Review by tjeaneric — CHANGES_REQUESTED** [review]
Add Pagination

**Review by tjeaneric — CHANGES_REQUESTED** [review]
Resolve conflict

**Comment by UmuhireJessie** [comment]
> Resolve conflict

resolved!

**Comment by UmuhireJessie** [comment]
> Add Pagination

Done!

**Review by furebo — APPROVED** [review]

**Pull request merged**
